### ISSUE TITLE
floorplan.yaml doesn't exist

### ISSUE THREAD

**Issue by ghost** [pkozul/ha-floorplan-kiosk#3]
From
[https://github.com/pkozul/ha-floorplan-kiosk/blob/master/README.md](url)

>#ha-floorplan-kiosk
>1)Update to the latest version of Floorplan (with support for Fully Kiosk) by copying the following file to the `www/custom_ui/floorplan` folder of Home Assistant:
>
>```
>https://raw.githubusercontent.com/pkozul/ha-floorplan-kiosk/master/floorplan.yaml
>```

https://raw.githubusercontent.com/pkozul/ha-floorplan-kiosk/master/floorplan.yaml

Link doesn't exist

**Comment by CCOSTAN** [comment]
addressed in #4

**Comment by pkozul** [comment]
Floorplan has been revamped. Please head over to to the new repo: https://github.com/ExperienceLovelace/ha-floorplan
