### ISSUE TITLE
Cannot read property 'EventsMixin' of undefined

### ISSUE THREAD

**Issue by CCOSTAN** [pkozul/ha-floorplan-kiosk#5]
```
2018-06-09 16:51:05 ERROR (MainThread) [frontend.js.latest.201805310]

/custom_ui/floorplan/ha-floorplan.html:82:47 Uncaught TypeError: Cannot read property 'EventsMixin' of undefined
```

Not sure where this error is stemming from but it is appearing on my Browser but still works fine in firetablet and kiosk browser. whew!

**Comment by pkozul** [comment]
Floorplan has been revamped. Please head over to to the new repo: https://github.com/ExperienceLovelace/ha-floorplan
