### ISSUE TITLE
Use without floorplan

### ISSUE THREAD

**Issue by freekeys** [pkozul/ha-floorplan-kiosk#7]
Hi,

I’m looking to set some fire tablets up with Lovelace and was wondering if the media player part of this repo will work without using floorplan?

So just the floorplan_mediaplayer custom component without floorplan being installed? Thanks!

**Comment by grewhit25** [comment]
I have pretty much the same requirements and was hoping to make use of all the features using a  Lovelace custom card for example but without the floorplan of course. 

It would appear that the custom component is tightly coupled with floorplan and the fully-kiosk library so making it difficult at the moment to use one without the other.

I am using a workaround at the min, by just placing the customized sensor in a Lovelace card and activate it from the firetablet, everything works just fine including tts to the tablet's speaker.

Here is a simple example I use to get fully-kiosk working from Lovelace:

- title: Firetablet
    panel: true
    cards:
      - type: picture-entity
        image: http://farm7.static.flickr.com/6153/6220100622_88e64ec5d8_b.jpg
        state_image:
          'on': http://farm7.static.flickr.com/6220/6220100616_a877f41a66_b.jpg
        entity: sensor.<customised_floorpan_sensor>

PS. Don't forget you also need the fire OS version of fully_kiosk.
PPS. I also commented out all the rules in floorplan.yaml.  Once you click on the sensor in Lovelace just close off the dialogue that pops up.

**Comment by pkozul** [comment]
Floorplan has been revamped. Please head over to to the new repo: https://github.com/ExperienceLovelace/ha-floorplan
